### ISSUE TITLE
Centering barcodes on the origin

### ISSUE THREAD

**Issue by dimo414** [X-Illuminati/glyphinator#4]
It would be great if there was a `center=true` option (or similar) so that it would be easier to position them relative to the center of a larger object. I've only played with `code_128()` so far but I don't see a way to center it, which means I have to manually position it approximately in the center of the object. This is tricky and tedious since the barcode's width is unpredictable.

Thanks for this library!

**Comment by dimo414** [comment]
Here's my workaround, based on visually positioning the barcode. It should work for `cs128_a`, as well, but `cs128_c` (numeric) will need different constants.

```
// Calls code_128(cs128_b(text)) but centers the barcode at the origin
// https://github.com/X-Illuminati/glyphinator/issues/4 would make this unnecessary.
module code_128b_centered(text, bar=1, space=0, quiet_zone=0) {
    // Observed values; may not be totally correct
    char_width=5.445;
    const_width=27.225;
    barcode_width = const_width+len(text)*char_width;

    // Height is scaled to 12.7mm (.5") tall
    // https://github.com/X-Illuminati/glyphinator/blob/f0051050/barcodes/code128.scad#L511
    translate([-barcode_width/2,-12.7/2,0])
        code_128(cs128_b(text), bar=bar, space=space, quiet_zone=quiet_zone);
}
```

**Comment by X-Illuminati** [comment]
Sorry, @dimo414 , I didn't see this issue request in 2021 -- I guess I didn't have email alerts set up for this repository. I'll add this to my todo list, but I don't know when I'll be able to get to it.

**Comment by X-Illuminati** [comment]
@dimo414 ,

Sorry to take so long to get back to this. Actually, for code_128, this is entirely trivial because the underlying bitmap library I am using already supports center=true. So, it is a just a matter of passing it along.

It will probably take a little longer to add it to the other symbologies since they don't all use that bitmap library uniformly. So, I will leave this issue open until I at least take a first look at them.

Also, in reference to your workaround mentioned above:
code_128 follows the standard scale for each module in the barcode (which is .495 mm x 12.7 mm). Most characters would be represented with 11 modules but there is also a 10 module quiet zone on either side of the barcode as well as a 13 module stop pattern at the end of the barcode. Additionally, the barcode will have a start pattern at the beginning and possibly additional code-switching patterns throughout it -- but these are all again multiples of 11 modules. And, finally, there is also a check digit added to the barcode right before the stop pattern.
So, in general, you could calculate the width as (.495 * 11 * (len(text)+5))/2, but you might have to increase the overhead from 5 to 6 or 7 depending on how many times you switch code sets.

Probably I will go ahead and add an extra function to explicitly calculate the width of the barcode, since this could be a useful helper function.

**Comment by X-Illuminati** [comment]
Just pushed commit b2c5db622c3bf6a88652686df98d410f83be3358 which adds a code_128_width() API function.

**Comment by X-Illuminati** [comment]
Added the center=true option and similar width/size API functions for the other symbologies:
- 50e8f4b36dec90a178e409bb9eb693c6c5382f35: code39
- 5438837e6f501a4a00f50b66b465362b6e812503: UPC-A/EAN-13
- dc35ebcca3b8bc409521a98cb3b541015d97beb5: datamatrix
- 88f35f0c871416c0e37db5ede0953fa26a31fb88: QR
